name: Node.js CI

on:
  push:
    branches: [ "main", "release", "develop" ]
  pull_request:
    branches: [ "main", "release", "develop" ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier
        run: yarn format

      - name: Commit changes
        env:
          MY_GITHUB_TOKEN: '${{ secrets.MY_GITHUB_TOKEN }}'
        run: |
          git config --local user.email "pedro.dev.oliveira@gmail.com"
          git config --local user.name "PedroDevOliveira"
          git config --global credential.helper cache
          git add -A
          git commit -m ":rotating_light: format code" -a || echo "No changes to commit"
          git push https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

  test:
    runs-on: ubuntu-latest
    needs: lint-and-format
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: __tests__/coverage
        flags: unittests
        name: codecov-umbrella
